# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod Properties
# Remember to change version in example property.
modVersion=3.1.8
mavenGroup=com.kotori316
archivesBaseName=scalable-cats-force-fabric
urlOfGitHub=https://github.com/Kotori316/SLP-fabric
mcStartVersion=26.1.0
# Other
branch=scala3
