name: Release

on: [ workflow_dispatch ] # Manual trigger

jobs:
  release:
    permissions:
      id-token: write
      contents: write
      packages: write
      attestations: write
    # See https://github.com/Kotori316/common-script/blob/main/.github/workflows/release-prod-gradle.yaml
    uses: 'Kotori316/common-script/.github/workflows/release-prod-gradle.yaml@main'
    with:
      release_command: 'checkReleaseVersion build publishMods publish registerVersion --stacktrace --no-daemon'
      enable_signature_check: false
      java_version: '21'
      use_attestation: true
      use_gradle_cache: true
    secrets: inherit
